name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout (recursive)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # ---------- Linux ----------
      - name: Install deps (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential xorg-dev mesa-common-dev libglfw3-dev
      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make -j"$(nproc)"
      - name: Check (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make check

      # ---------- Windows ----------
      - name: Set up MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            make
          update: true
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          make -j2 OS=Windows_NT
      - name: Check (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          make check OS=Windows_NT
