name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libglfw3-dev libglfw3 xorg-dev

    - name: Build project
      run: make -C src

    - name: Run test create particle
      run: make -C tests test_create_particle

    - name: Run test movement
      run: make -C tests test_movement
